# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "E:/la32r_soc_ciciec/la32r_soc_ciciec/fpga/project/Loongson_Soc.runs/synth_1/soc_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 5
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tfbg676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/la32r_soc_ciciec/la32r_soc_ciciec/fpga/project/Loongson_Soc.cache/wt [current_project]
set_property parent.project_path E:/la32r_soc_ciciec/la32r_soc_ciciec/fpga/project/Loongson_Soc.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/la32r_soc_ciciec/la32r_soc_ciciec/fpga/project/Loongson_Soc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files -quiet E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/PLL_2019_2/clk_pll.dcp
set_property used_in_implementation false [get_files E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/PLL_2019_2/clk_pll.dcp]
read_verilog {
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/open-la500/csr.h
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/config.h
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/open-la500/mycpu.h
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/APB_UART/URT/uart_defines.h
}
set_property file_type "Verilog Header" [get_files E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/open-la500/csr.h]
set_property file_type "Verilog Header" [get_files E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/config.h]
set_property file_type "Verilog Header" [get_files E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/open-la500/mycpu.h]
set_property file_type "Verilog Header" [get_files E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/APB_UART/URT/uart_defines.h]
read_verilog -library xil_defaultlib {
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/Bus_interconnects/AxiCrossbar_1x4.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/Bus_interconnects/Axi_CDC.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/open-la500/addr_trans.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/open-la500/alu.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/APB_UART/apb_mux2.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/APB_UART/axi2apb.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/Bus_interconnects/axi2sram_sp_ext.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/open-la500/axi_bridge.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/APB_UART/axi_uart_controller.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/ram_wrap/axi_wrap_ram_sp_ext.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/open-la500/btb.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/ram_wrap/cache_sram.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/PLL_2019_2/clk_pll_stub.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/confreg/confreg.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/open-la500/csr.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/open-la500/dcache.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/confreg/digitaltube_controller.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/open-la500/div.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/open-la500/exe_stage.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/open-la500/icache.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/open-la500/id_stage.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/open-la500/if_stage.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/confreg/lcd_driver.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/open-la500/mem_stage.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/open-la500/mul.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/open-la500/mycpu_top.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/open-la500/perf_counter.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/APB_UART/URT/raminfr.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/open-la500/regfile.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/rst_sync/rst_sync.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/open-la500/tlb_entry.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/open-la500/tools.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/APB_UART/URT/uart_receiver.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/APB_UART/URT/uart_regs.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/APB_UART/URT/uart_rfifo.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/APB_UART/URT/uart_sync_flops.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/APB_UART/URT/uart_tfifo.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/APB_UART/URT/uart_top.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/APB_UART/URT/uart_transmitter.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/ip/open-la500/wb_stage.v
  E:/la32r_soc_ciciec/la32r_soc_ciciec/rtl/soc_top.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/la32r_soc_ciciec/la32r_soc_ciciec/fpga/constraints/soc.xdc
set_property used_in_implementation false [get_files E:/la32r_soc_ciciec/la32r_soc_ciciec/fpga/constraints/soc.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top soc_top -part xc7a200tfbg676-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file soc_top_utilization_synth.rpt -pb soc_top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
